/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lfattribute;

/**
 *
 * @author terence Brawley copyright, all rights reserved
 * 
 * Introduction - For those of you reading this, this little project was written for 
 * the purposes of a job search.  A little background is in order.  I have many years of
 * experience as a developer, but the last time I focused solely on that was about ten years ago.
 * 
 * I really enjoyed putting this thing together.  I am working on a longer term, larger project
 * and this was a great way to get me back into Java.  I had initially thought I would
 * submit this a few days earlier, but I wanted to include just a little more functionality,
 * so I took the weekend to provide that.  Having said that, there are things that I would do differently
 * if the target for this project was larger.  I will specify some of those things below.
 * 
 * Security - I broke the rules in several ways for this project, and I would certainly implement
 * things differently if this was ever expected to go into production.  On the database side, 
 * I did two things that are frowned upon.  I made the password to the db user identical
 * to the user name and I also granted the user the DBA role.  This is really only ok if you are working 
 * on a toy that will never see public use.
 * 
 * Also, I hard coded the connection information directly into the code, which is also
 * not good practice.  I would put information like this into a configuration file and 
 * then write a method to collect that information in a safe manner.
 * 
 * Design - Overall, the design of this is completely too simplistic.  It would need better UI
 * design, probably making use of JSP or HTML with CSS.  Alas, this is something I am ignorant of at the
 * moment.  
 * 
 * Given the scope of what it is, I would still do things a little differently if I wanted to put
 * another couple days in.  First, I would create a more central error handling methodology with
 * errors being put into their own dialog boxes rather than a simple label on the form.  Second,
 * I would put in some business logic to validate the entries that were being input into the forms
 * and throw exceptions to be handled and provide messages to the user. 
 * 
 * I would also include some automated testing using JUnit.  That looks like a required method
 * of ensuring quality and integrating the developer and QA teams together.
 * 
 * Also, given where this project is going and the template of the one table.  I would include
 * more tables of the Character Generator.
 * 
 * The thing I found was just how much fun I had doing this.  It has been a long time since
 * I did something creative like this on the computer, I have mostly been focused on the nuts
 * and bolts of keeping a very large database available, performant and recoverable.
 * 
 * This was a very nice change.
 * 
 * Thanks for reading this and I look forward to meeting with you soon.

 */
public class LFAttribute extends javax.swing.JFrame {

    /**
     * Creates new form LFAttribute
     */
    public LFAttribute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Quit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddAttribute dialog = new AddAttribute(new javax.swing.JFrame(), true); 

        dialog.setVisible(true);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SelAttribute dialog = new SelAttribute(new javax.swing.JFrame(), true); 

        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LFAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LFAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LFAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LFAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LFAttribute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables



}

