CREATE TABLE SKILLS 
(
  SKILL_ID NUMBER NOT NULL 
, SKILL_NAME VARCHAR2(40) NOT NULL 
, CONSTRAINT SKILLS_PK PRIMARY KEY 
  (
    SKILL_ID 
  )
  ENABLE 
) 
TABLESPACE LIFEFORCE_DATA 
STORAGE 
( 
  INITIAL 10485760 
  NEXT 10485760 
  MAXEXTENTS UNLIMITED 
);

